### ISSUE TITLE
Need help transferred to request coins wallet address and not actual wallet address 

### ISSUE THREAD

**Issue by Kirankumar-kulkarni** [langerhans/dogecoin-wallet-new#48]
My issue #47 was addressed and closed. Can I know difference between request coins address and wallet address. Also can I know whose address is DGqiFMRWEqzJNp1QvVYoysVPYDHeeC5UBh.
How can I contact him. This will help me get back my coins. Thanks a lot for your kind support.

**Comment by langerhans** [comment]
There is no difference at all. If this is the address the wallet gave you it is your address. But since you uninstalled the app without making a backup you lost access to it. Even if it wasn't your address, how would I know whose address it is? I know this sounds harsh, but your coins are gone. Let this be a lesson about following the advice you were given by the wallet about backups. Those messages are there for a reason. Please refrain from opening more issues as this is not a software issue.
