### ISSUE TITLE
spending pin

### ISSUE THREAD

**Issue by borx84** [langerhans/dogecoin-wallet-new#50]
hello,

whats wrong with this wallet??! I havent activated no kind of pin etc  but this wallet is searching pin if i want to send coins...and now i have coins traped in this wallet -usles....

how can i fix that ,is there any chance?

**Comment by langerhans** [comment]
Not with that attitude, no.
You need to remember the PIN. The wallet doesn't magically do that by itself.

**Comment by borx84** [comment]
Well sorry im a bit stressed out...i havent set any pin or what so ever ,there was not even question about such thing...i have few wallets for other coins and i have written down on paper every code etc,but by this wallet i have simply just loged in --i have nothing so this code request had stuned me .....i took this wallet because on other doge wallet isnt possible to scan code and i have coins on a paper wallet and now some of it is traped here and i have no clue where to search or what to do

**Comment by langerhans** [comment]
Okay, I went back to check the code. There are exactly two places that can even encrypt the wallet:
1) https://github.com/langerhans/dogecoin-wallet-new/blob/master/wallet/src/de/schildbach/wallet/ui/EncryptKeysDialogFragment.java which is the UI for setting and changing the PIN
2) https://github.com/langerhans/dogecoin-wallet-new/blob/master/wallet/src/de/schildbach/wallet/ui/send/DeriveKeyTask.java which can only be run if the wallet was already encrypted. 

So I honestly can't tell you how the wallet was supposed to end up encrypted by itself. Your solution would be to restore from a backup from before this happened, which you kept safe somewhere, right? Cause if not you're out of luck, but you should have that since the wallet told you to.

**Comment by borx84** [comment]
I dont believe that i've made any backup yet,and the wallet is totaly fresh created.... 
Ok,thank you wery much for your help..I'll see if anything can be done with those links you send it,thanks..if not,than i'll just have to accept the lose and be more carefull  next time...

**Comment by btc2dogecom** [comment]
> I dont believe that i've made any backup yet,and the wallet is totaly fresh created....
> Ok,thank you wery much for your help..I'll see if anything can be done with those links you send it,thanks..if not,than i'll just have to accept the lose and be more carefull next time...

can help you recover the PIN if it is not too long. www.btc2doge.com

**Comment by doge2021** [comment]
> I dont believe that i've made any backup yet,and the wallet is totaly fresh created.... Ok,thank you wery much for your help..I'll see if anything can be done with those links you send it,thanks..if not,than i'll just have to accept the lose and be more carefull next time...

you can reach https://btc2doge.org/dogecoin-recovery/ if you need help. he recovered my 368k in 2021
